### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by baggepinnen** [baggepinnen/BlobTracking.jl#1]
- [x] Separate update for tracker
- [ ] Push collections to buffer
- [ ] Collect video 
- [x] Trace for each blob 
- [x] Trace of positions, predictions and measurements 
- [x] Post analysis 
- [ ] Composable temporal filters
- [x] Visualization
- [ ] Auto tuning of covariance, smart defaults for size
- [x] Correspondence type with Hungarian or nearest neighbor as naive default 
- [ ] Replay tracking with different options
- [ ] Run multiple tracking configurations at the same time
- [ ] MonteCarlo correspondence
